name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Set up
    runs-on: ubuntu-20.04

    steps:
      - name: Do things to set up
        run: echo "Set up complete!"

  job2:
    name: Build
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        bld_no: [1, 2, 3]

    steps:
      - name: Do things to build
        run: |
          sleep 60
          cat ${GITHUB_EVENT_PATH}
          echo "Build ${{ matrix.bld_no }} complete!"
    
  job3:
    name: Test
    needs: job2
    runs-on: ubuntu-20.04

    steps:
      - name: Do things to test
        run: |
          sleep 60
          echo "Test complete!"
